[2023-01-28T14:14:54.943+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: my_second_dagV5.insert_task manual__2023-01-28T14:14:51.682123+00:00 [queued]>
[2023-01-28T14:14:54.951+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: my_second_dagV5.insert_task manual__2023-01-28T14:14:51.682123+00:00 [queued]>
[2023-01-28T14:14:54.951+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-01-28T14:14:54.951+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2023-01-28T14:14:54.951+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-01-28T14:14:55.034+0000] {taskinstance.py:1300} INFO - Executing <Task(PostgresOperator): insert_task> on 2023-01-28 14:14:51.682123+00:00
[2023-01-28T14:14:55.039+0000] {standard_task_runner.py:55} INFO - Started process 22819 to run task
[2023-01-28T14:14:55.042+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'my_second_dagV5', 'insert_task', 'manual__2023-01-28T14:14:51.682123+00:00', '--job-id', '52', '--raw', '--subdir', 'DAGS_FOLDER/dag2.py', '--cfg-path', '/tmp/tmp3oyxh0bv']
[2023-01-28T14:14:55.042+0000] {standard_task_runner.py:83} INFO - Job 52: Subtask insert_task
[2023-01-28T14:14:55.098+0000] {task_command.py:388} INFO - Running <TaskInstance: my_second_dagV5.insert_task manual__2023-01-28T14:14:51.682123+00:00 [running]> on host 9763ece73850
[2023-01-28T14:14:55.205+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=my_second_dagV5
AIRFLOW_CTX_TASK_ID=insert_task
AIRFLOW_CTX_EXECUTION_DATE=2023-01-28T14:14:51.682123+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-01-28T14:14:51.682123+00:00
[2023-01-28T14:14:55.206+0000] {sql.py:254} INFO - Executing: 
            insert into dag_runs(dt, dag_id) VALUES (%(ds)s, 'dag is dag not a dag22')
        
[2023-01-28T14:14:55.213+0000] {base.py:73} INFO - Using connection ID 'postgres_localhost' for task execution.
[2023-01-28T14:14:55.392+0000] {base.py:73} INFO - Using connection ID 'postgres_localhost' for task execution.
[2023-01-28T14:14:55.395+0000] {sql.py:375} INFO - Running statement: 
            insert into dag_runs(dt, dag_id) VALUES (%(ds)s, 'dag is dag not a dag22')
        , parameters: {'ds': datetime.datetime(2022, 2, 13, 0, 0)}
[2023-01-28T14:14:55.396+0000] {sql.py:384} INFO - Rows affected: 1
[2023-01-28T14:14:55.425+0000] {taskinstance.py:1323} INFO - Marking task as SUCCESS. dag_id=my_second_dagV5, task_id=insert_task, execution_date=20230128T141451, start_date=20230128T141454, end_date=20230128T141455
[2023-01-28T14:14:55.496+0000] {local_task_job.py:208} INFO - Task exited with return code 0
[2023-01-28T14:14:55.515+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
