[2023-05-18T13:14:20.811+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: my_third_dagV5.fo manual__2023-05-18T13:14:20.033279+00:00 [queued]>
[2023-05-18T13:14:20.821+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: my_third_dagV5.fo manual__2023-05-18T13:14:20.033279+00:00 [queued]>
[2023-05-18T13:14:20.821+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-05-18T13:14:20.821+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2023-05-18T13:14:20.821+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-05-18T13:14:20.833+0000] {taskinstance.py:1300} INFO - Executing <Task(PythonOperator): fo> on 2023-05-18 13:14:20.033279+00:00
[2023-05-18T13:14:20.840+0000] {standard_task_runner.py:55} INFO - Started process 28729 to run task
[2023-05-18T13:14:20.843+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'my_third_dagV5', 'fo', 'manual__2023-05-18T13:14:20.033279+00:00', '--job-id', '180', '--raw', '--subdir', 'DAGS_FOLDER/dag3.py', '--cfg-path', '/tmp/tmpu65zv6l3']
[2023-05-18T13:14:20.843+0000] {standard_task_runner.py:83} INFO - Job 180: Subtask fo
[2023-05-18T13:14:20.932+0000] {task_command.py:388} INFO - Running <TaskInstance: my_third_dagV5.fo manual__2023-05-18T13:14:20.033279+00:00 [running]> on host 031cfb56e8fb
[2023-05-18T13:14:21.009+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=my_third_dagV5
AIRFLOW_CTX_TASK_ID=fo
AIRFLOW_CTX_EXECUTION_DATE=2023-05-18T13:14:20.033279+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-05-18T13:14:20.033279+00:00
[2023-05-18T13:14:33.933+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/pyspark/context.py:317: FutureWarning: Python 3.7 support is deprecated in Spark 3.4.
  warnings.warn("Python 3.7 support is deprecated in Spark 3.4.", FutureWarning)

[2023-05-18T13:14:34.042+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dag3.py", line 73, in foo1
    sc = spark_session.sparkContext
NameError: name 'spark_session' is not defined
[2023-05-18T13:14:34.050+0000] {taskinstance.py:1323} INFO - Marking task as FAILED. dag_id=my_third_dagV5, task_id=fo, execution_date=20230518T131420, start_date=20230518T131420, end_date=20230518T131434
[2023-05-18T13:14:34.079+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 180 for task fo (name 'spark_session' is not defined; 28729)
[2023-05-18T13:14:34.118+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2023-05-18T13:14:34.132+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
