[2023-05-16T12:56:15.284+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: my_third_dagV4.fo manual__2023-05-16T12:56:13.588775+00:00 [queued]>
[2023-05-16T12:56:15.295+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: my_third_dagV4.fo manual__2023-05-16T12:56:13.588775+00:00 [queued]>
[2023-05-16T12:56:15.295+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-05-16T12:56:15.295+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2023-05-16T12:56:15.295+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-05-16T12:56:15.313+0000] {taskinstance.py:1300} INFO - Executing <Task(PythonOperator): fo> on 2023-05-16 12:56:13.588775+00:00
[2023-05-16T12:56:15.320+0000] {standard_task_runner.py:55} INFO - Started process 13060 to run task
[2023-05-16T12:56:15.324+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'my_third_dagV4', 'fo', 'manual__2023-05-16T12:56:13.588775+00:00', '--job-id', '150', '--raw', '--subdir', 'DAGS_FOLDER/dag3.py', '--cfg-path', '/tmp/tmpids8tjlj']
[2023-05-16T12:56:15.325+0000] {standard_task_runner.py:83} INFO - Job 150: Subtask fo
[2023-05-16T12:56:15.433+0000] {task_command.py:388} INFO - Running <TaskInstance: my_third_dagV4.fo manual__2023-05-16T12:56:13.588775+00:00 [running]> on host d1c47018cb38
[2023-05-16T12:56:15.697+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=my_third_dagV4
AIRFLOW_CTX_TASK_ID=fo
AIRFLOW_CTX_EXECUTION_DATE=2023-05-16T12:56:13.588775+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-05-16T12:56:13.588775+00:00
[2023-05-16T12:56:31.234+0000] {logging_mixin.py:137} INFO - Hello
[2023-05-16T12:56:31.234+0000] {logging_mixin.py:137} INFO - <pyspark.sql.session.SparkSession object at 0x7fcf2a4f4510>
[2023-05-16T12:56:31.234+0000] {logging_mixin.py:137} INFO - Bye
[2023-05-16T12:56:32.134+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dag3.py", line 93, in foo1
    .option("driver", "org.postgresql.Driver") \
  File "/home/airflow/.local/lib/python3.7/site-packages/pyspark/sql/readwriter.py", line 184, in load
    return self._df(self._jreader.load())
  File "/home/airflow/.local/lib/python3.7/site-packages/py4j/java_gateway.py", line 1322, in __call__
    answer, self.gateway_client, self.target_id, self.name)
  File "/home/airflow/.local/lib/python3.7/site-packages/pyspark/sql/utils.py", line 196, in deco
    raise converted from None
pyspark.sql.utils.AnalysisException: Found duplicate column(s) in the data schema: `product_id`
[2023-05-16T12:56:32.164+0000] {taskinstance.py:1323} INFO - Marking task as FAILED. dag_id=my_third_dagV4, task_id=fo, execution_date=20230516T125613, start_date=20230516T125615, end_date=20230516T125632
[2023-05-16T12:56:32.177+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 150 for task fo (Found duplicate column(s) in the data schema: `product_id`; 13060)
[2023-05-16T12:56:32.230+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2023-05-16T12:56:32.250+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
