[2023-01-28T07:51:36.905+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: my_second_dagV3.insert_task manual__2023-01-28T07:51:34.225844+00:00 [queued]>
[2023-01-28T07:51:36.915+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: my_second_dagV3.insert_task manual__2023-01-28T07:51:34.225844+00:00 [queued]>
[2023-01-28T07:51:36.916+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-01-28T07:51:36.916+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2023-01-28T07:51:36.916+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-01-28T07:51:36.948+0000] {taskinstance.py:1300} INFO - Executing <Task(PostgresOperator): insert_task> on 2023-01-28 07:51:34.225844+00:00
[2023-01-28T07:51:36.953+0000] {standard_task_runner.py:55} INFO - Started process 6444 to run task
[2023-01-28T07:51:36.960+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'my_second_dagV3', 'insert_task', 'manual__2023-01-28T07:51:34.225844+00:00', '--job-id', '25', '--raw', '--subdir', 'DAGS_FOLDER/dag2.py', '--cfg-path', '/tmp/tmp0f51agkj']
[2023-01-28T07:51:36.960+0000] {standard_task_runner.py:83} INFO - Job 25: Subtask insert_task
[2023-01-28T07:51:37.050+0000] {task_command.py:388} INFO - Running <TaskInstance: my_second_dagV3.insert_task manual__2023-01-28T07:51:34.225844+00:00 [running]> on host 9763ece73850
[2023-01-28T07:51:37.179+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=my_second_dagV3
AIRFLOW_CTX_TASK_ID=insert_task
AIRFLOW_CTX_EXECUTION_DATE=2023-01-28T07:51:34.225844+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-01-28T07:51:34.225844+00:00
[2023-01-28T07:51:37.180+0000] {sql.py:254} INFO - Executing: 
            insert into dag_runs(dt, dag_id) VALUES ('2022-02-09 00:00:00', 'dag is dag not a dag')
        
[2023-01-28T07:51:37.188+0000] {base.py:73} INFO - Using connection ID 'postgres_localhost' for task execution.
[2023-01-28T07:51:37.401+0000] {base.py:73} INFO - Using connection ID 'postgres_localhost' for task execution.
[2023-01-28T07:51:37.405+0000] {sql.py:375} INFO - Running statement: 
            insert into dag_runs(dt, dag_id) VALUES ('2022-02-09 00:00:00', 'dag is dag not a dag')
        , parameters: None
[2023-01-28T07:51:37.406+0000] {sql.py:384} INFO - Rows affected: 1
[2023-01-28T07:51:37.421+0000] {taskinstance.py:1323} INFO - Marking task as SUCCESS. dag_id=my_second_dagV3, task_id=insert_task, execution_date=20230128T075134, start_date=20230128T075136, end_date=20230128T075137
[2023-01-28T07:51:37.453+0000] {local_task_job.py:208} INFO - Task exited with return code 0
[2023-01-28T07:51:37.469+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
