[2023-01-29T07:38:39.299+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: my_second_dagV5.save_new_data scheduled__2023-01-22T00:00:00+00:00 [queued]>
[2023-01-29T07:38:39.314+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: my_second_dagV5.save_new_data scheduled__2023-01-22T00:00:00+00:00 [queued]>
[2023-01-29T07:38:39.314+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-01-29T07:38:39.315+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2023-01-29T07:38:39.315+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-01-29T07:38:39.364+0000] {taskinstance.py:1300} INFO - Executing <Task(PostgresOperator): save_new_data> on 2023-01-22 00:00:00+00:00
[2023-01-29T07:38:39.373+0000] {standard_task_runner.py:55} INFO - Started process 48100 to run task
[2023-01-29T07:38:39.376+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'my_second_dagV5', 'save_new_data', 'scheduled__2023-01-22T00:00:00+00:00', '--job-id', '61', '--raw', '--subdir', 'DAGS_FOLDER/dag2.py', '--cfg-path', '/tmp/tmpf4qd1qcw']
[2023-01-29T07:38:39.377+0000] {standard_task_runner.py:83} INFO - Job 61: Subtask save_new_data
[2023-01-29T07:38:39.553+0000] {task_command.py:388} INFO - Running <TaskInstance: my_second_dagV5.save_new_data scheduled__2023-01-22T00:00:00+00:00 [running]> on host 9763ece73850
[2023-01-29T07:38:39.700+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=my_second_dagV5
AIRFLOW_CTX_TASK_ID=save_new_data
AIRFLOW_CTX_EXECUTION_DATE=2023-01-22T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-01-22T00:00:00+00:00
[2023-01-29T07:38:39.701+0000] {sql.py:254} INFO - Executing: 
            CREATE TABLE IF NOT EXISTS dag_runs (
                dt date, 
                dag_id character varying,
                PRIMARY KEY (dt, dag_id)
            )
          
[2023-01-29T07:38:39.713+0000] {base.py:73} INFO - Using connection ID 'postgres_localhost' for task execution.
[2023-01-29T07:38:39.979+0000] {base.py:73} INFO - Using connection ID 'postgres_localhost' for task execution.
[2023-01-29T07:38:39.986+0000] {sql.py:375} INFO - Running statement: 
            CREATE TABLE IF NOT EXISTS dag_runs (
                dt date, 
                dag_id character varying,
                PRIMARY KEY (dt, dag_id)
            )
          , parameters: None
[2023-01-29T07:38:39.999+0000] {taskinstance.py:1323} INFO - Marking task as SUCCESS. dag_id=my_second_dagV5, task_id=save_new_data, execution_date=20230122T000000, start_date=20230129T073839, end_date=20230129T073839
[2023-01-29T07:38:40.073+0000] {local_task_job.py:208} INFO - Task exited with return code 0
[2023-01-29T07:38:40.101+0000] {taskinstance.py:2578} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2023-01-31T09:00:41.933+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: my_second_dagV5.save_new_data scheduled__2023-01-22T00:00:00+00:00 [queued]>
[2023-01-31T09:00:41.987+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: my_second_dagV5.save_new_data scheduled__2023-01-22T00:00:00+00:00 [queued]>
[2023-01-31T09:00:41.987+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-01-31T09:00:41.987+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2023-01-31T09:00:41.987+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-01-31T09:00:42.018+0000] {taskinstance.py:1300} INFO - Executing <Task(PostgresOperator): save_new_data> on 2023-01-22 00:00:00+00:00
[2023-01-31T09:00:42.029+0000] {standard_task_runner.py:55} INFO - Started process 591 to run task
[2023-01-31T09:00:42.055+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'my_second_dagV5', 'save_new_data', 'scheduled__2023-01-22T00:00:00+00:00', '--job-id', '8', '--raw', '--subdir', 'DAGS_FOLDER/dag2.py', '--cfg-path', '/tmp/tmpglfqjkrg']
[2023-01-31T09:00:42.080+0000] {standard_task_runner.py:83} INFO - Job 8: Subtask save_new_data
[2023-01-31T09:00:42.397+0000] {task_command.py:388} INFO - Running <TaskInstance: my_second_dagV5.save_new_data scheduled__2023-01-22T00:00:00+00:00 [running]> on host ab5131891604
[2023-01-31T09:00:42.727+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=my_second_dagV5
AIRFLOW_CTX_TASK_ID=save_new_data
AIRFLOW_CTX_EXECUTION_DATE=2023-01-22T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-01-22T00:00:00+00:00
[2023-01-31T09:00:42.727+0000] {sql.py:254} INFO - Executing: 
            CREATE TABLE IF NOT EXISTS dag_runs (
                dt date, 
                dag_id character varying,
                PRIMARY KEY (dt, dag_id)
            )
          
[2023-01-31T09:00:42.745+0000] {base.py:73} INFO - Using connection ID 'postgres_localhost' for task execution.
[2023-01-31T09:00:43.447+0000] {base.py:73} INFO - Using connection ID 'postgres_localhost' for task execution.
[2023-01-31T09:00:43.451+0000] {sql.py:375} INFO - Running statement: 
            CREATE TABLE IF NOT EXISTS dag_runs (
                dt date, 
                dag_id character varying,
                PRIMARY KEY (dt, dag_id)
            )
          , parameters: None
[2023-01-31T09:00:43.475+0000] {taskinstance.py:1323} INFO - Marking task as SUCCESS. dag_id=my_second_dagV5, task_id=save_new_data, execution_date=20230122T000000, start_date=20230131T090041, end_date=20230131T090043
[2023-01-31T09:00:43.528+0000] {local_task_job.py:208} INFO - Task exited with return code 0
[2023-01-31T09:00:43.555+0000] {taskinstance.py:2578} INFO - 1 downstream tasks scheduled from follow-on schedule check
