[2023-05-18T14:02:45.084+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: my_first_dagV2.get_save_new_data manual__2023-05-18T14:02:42.561848+00:00 [queued]>
[2023-05-18T14:02:45.132+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: my_first_dagV2.get_save_new_data manual__2023-05-18T14:02:42.561848+00:00 [queued]>
[2023-05-18T14:02:45.132+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-05-18T14:02:45.132+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2023-05-18T14:02:45.133+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-05-18T14:02:45.153+0000] {taskinstance.py:1300} INFO - Executing <Task(PythonOperator): get_save_new_data> on 2023-05-18 14:02:42.561848+00:00
[2023-05-18T14:02:45.159+0000] {standard_task_runner.py:55} INFO - Started process 32825 to run task
[2023-05-18T14:02:45.170+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'my_first_dagV2', 'get_save_new_data', 'manual__2023-05-18T14:02:42.561848+00:00', '--job-id', '186', '--raw', '--subdir', 'DAGS_FOLDER/dag1.py', '--cfg-path', '/tmp/tmptfuxv8vv']
[2023-05-18T14:02:45.171+0000] {standard_task_runner.py:83} INFO - Job 186: Subtask get_save_new_data
[2023-05-18T14:02:45.292+0000] {task_command.py:388} INFO - Running <TaskInstance: my_first_dagV2.get_save_new_data manual__2023-05-18T14:02:42.561848+00:00 [running]> on host 031cfb56e8fb
[2023-05-18T14:02:45.452+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=my_first_dagV2
AIRFLOW_CTX_TASK_ID=get_save_new_data
AIRFLOW_CTX_EXECUTION_DATE=2023-05-18T14:02:42.561848+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-05-18T14:02:42.561848+00:00
[2023-05-18T14:02:45.453+0000] {python.py:177} INFO - Done. Returned value was: 2
[2023-05-18T14:02:45.553+0000] {taskinstance.py:1323} INFO - Marking task as SUCCESS. dag_id=my_first_dagV2, task_id=get_save_new_data, execution_date=20230518T140242, start_date=20230518T140245, end_date=20230518T140245
[2023-05-18T14:02:45.623+0000] {local_task_job.py:208} INFO - Task exited with return code 0
[2023-05-18T14:02:45.760+0000] {taskinstance.py:2578} INFO - 1 downstream tasks scheduled from follow-on schedule check
