[2023-01-28T07:44:09.612+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: my_second_dagV3.save_new_data scheduled__2023-01-15T00:00:00+00:00 [queued]>
[2023-01-28T07:44:09.800+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: my_second_dagV3.save_new_data scheduled__2023-01-15T00:00:00+00:00 [queued]>
[2023-01-28T07:44:09.800+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-01-28T07:44:09.800+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2023-01-28T07:44:09.800+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-01-28T07:44:09.838+0000] {taskinstance.py:1300} INFO - Executing <Task(PostgresOperator): save_new_data> on 2023-01-15 00:00:00+00:00
[2023-01-28T07:44:09.844+0000] {standard_task_runner.py:55} INFO - Started process 5912 to run task
[2023-01-28T07:44:09.848+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'my_second_dagV3', 'save_new_data', 'scheduled__2023-01-15T00:00:00+00:00', '--job-id', '19', '--raw', '--subdir', 'DAGS_FOLDER/dag2.py', '--cfg-path', '/tmp/tmpz3hnr9us']
[2023-01-28T07:44:09.848+0000] {standard_task_runner.py:83} INFO - Job 19: Subtask save_new_data
[2023-01-28T07:44:10.203+0000] {task_command.py:388} INFO - Running <TaskInstance: my_second_dagV3.save_new_data scheduled__2023-01-15T00:00:00+00:00 [running]> on host 9763ece73850
[2023-01-28T07:44:10.832+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=my_second_dagV3
AIRFLOW_CTX_TASK_ID=save_new_data
AIRFLOW_CTX_EXECUTION_DATE=2023-01-15T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-01-15T00:00:00+00:00
[2023-01-28T07:44:10.832+0000] {sql.py:254} INFO - Executing: 
            CREATE TABLE IF NOT EXISTS dag_runs (
                dt date, 
                dag_id character varying,
                PRIMARY KEY (dt, dag_id)
            )
          
[2023-01-28T07:44:10.962+0000] {base.py:73} INFO - Using connection ID 'postgres_localhost' for task execution.
[2023-01-28T07:44:13.885+0000] {base.py:73} INFO - Using connection ID 'postgres_localhost' for task execution.
[2023-01-28T07:44:13.889+0000] {sql.py:375} INFO - Running statement: 
            CREATE TABLE IF NOT EXISTS dag_runs (
                dt date, 
                dag_id character varying,
                PRIMARY KEY (dt, dag_id)
            )
          , parameters: None
[2023-01-28T07:44:13.978+0000] {taskinstance.py:1323} INFO - Marking task as SUCCESS. dag_id=my_second_dagV3, task_id=save_new_data, execution_date=20230115T000000, start_date=20230128T074409, end_date=20230128T074413
[2023-01-28T07:44:14.062+0000] {local_task_job.py:208} INFO - Task exited with return code 0
[2023-01-28T07:44:14.200+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
